version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: stockdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"   # за връзка от .NET
      - "15672:15672" # web UI за RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword

  orderservice:
    build: ./Services/OrderService
    container_name: orderservice
    ports:
      - "5001:80"
    depends_on:
      - postgres
      - rabbitmq

  portfolioservice:
    build: ./Services/PortfolioService
    container_name: portfolioservice
    ports:
      - "5002:80"
    depends_on:
      - postgres
      - rabbitmq

  priceservice:
    build: ./Services/PriceService
    container_name: priceservice
    ports:
      - "5003:80"
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
